#!/bin/bash

START_PWD=`pwd -P`
cd `dirname $BASH_SOURCE`/../..
CONTEXT_ROOT=`pwd -P`
cd ~
HOME_DIR=`pwd -P`

echo
echo ...redis
echo

cd $CONTEXT_ROOT
docker stop laravel-redis &> /dev/null
docker rm laravel-redis &> /dev/null
docker rmi laravel-redis &> /dev/null
docker build --tag="laravel-redis" --file="./images/redis/Dockerfile" $CONTEXT_ROOT

cd $START_PWD