#!/bin/bash

START_PWD=`pwd -P`
cd `dirname $BASH_SOURCE`
CONTEXT_ROOT=`pwd -P`
cd ~
HOME_DIR=`pwd -P`

cd $START_PWD

docker stop laravel-php-composer &> /dev/null
docker rm laravel-php-composer &> /dev/null
docker run -i -t --volume=$HOME_DIR/.ssh:/root/.host-ssh --volume=$CONTEXT_ROOT/laravel:/var/www --name=laravel-php-composer laravel-php-cli php /composer.phar "$@"