#!/bin/bash

START_PWD=`pwd -P`
cd `dirname $BASH_SOURCE`/../..
CONTEXT_ROOT=`pwd -P`
cd ~
HOME_DIR=`pwd -P`

echo
echo ...nginx
echo

cd $CONTEXT_ROOT
docker stop laravel-nginx &> /dev/null
docker rm laravel-nginx &> /dev/null
docker rmi laravel-nginx &> /dev/null
docker build --tag="laravel-nginx" --file="./images/nginx/Dockerfile" $CONTEXT_ROOT

cd $START_PWD