#!/bin/bash

START_PWD=`pwd -P`
cd `dirname $BASH_SOURCE`/../..
CONTEXT_ROOT=`pwd -P`
cd ~
HOME_DIR=`pwd -P`

cd $CONTEXT_ROOT
docker stop laravel-nginx &> /dev/null
docker rm laravel-nginx &> /dev/null
docker run -d --publish=8080:8080 --volume=$CONTEXT_ROOT/laravel/public:/var/www/public --name=laravel-nginx --link=laravel-php-fpm:php-fpm laravel-nginx

cd $START_PWD