#!/bin/bash

START_PWD=`pwd -P`
cd `dirname $BASH_SOURCE`/../..
CONTEXT_ROOT=`pwd -P`
cd ~
HOME_DIR=`pwd -P`

echo
echo ...postgres
echo

cd $CONTEXT_ROOT
docker stop laravel-postgres &> /dev/null
docker rm laravel-postgres &> /dev/null
docker rmi laravel-postgres &> /dev/null
docker build --tag="laravel-postgres" --file="./images/postgres/Dockerfile" $CONTEXT_ROOT

cd $START_PWD