#!/bin/bash

START_PWD=`pwd -P`
cd `dirname $BASH_SOURCE`/..
CONTEXT_ROOT=`pwd -P`
cd ~
HOME_DIR=`pwd -P`

echo
echo Building images...
echo

cd $CONTEXT_ROOT

./images/data/build
./images/redis/build
./images/postgres/build
./images/php-cli/build
./images/php-fpm/build
./images/nginx/build

echo
echo Build complete!
echo

docker images

echo

cd $START_PWD