#!/bin/bash

START_PWD=`pwd -P`
cd `dirname $BASH_SOURCE`/..
CONTEXT_ROOT=`pwd -P`
cd ~
HOME_DIR=`pwd -P`

echo
echo Creating development environment...
echo

cd $CONTEXT_ROOT

./images/data/develop
./images/redis/develop
./images/postgres/develop
./images/php-fpm/develop
./images/nginx/develop

echo

docker ps

echo

cd $START_PWD