#!/bin/bash

START_PWD=`pwd -P`
cd `dirname $BASH_SOURCE`/../..
CONTEXT_ROOT=`pwd -P`
cd ~
HOME_DIR=`pwd -P`

echo
echo ...php-cli
echo

cd $CONTEXT_ROOT

docker stop laravel-php-cli &> /dev/null
docker rm laravel-php-cli &> /dev/null
docker rmi laravel-php-cli &> /dev/null
docker build --tag="laravel-php-cli" --file="./images/php-cli/Dockerfile" $CONTEXT_ROOT

cd $START_PWD